"use client";
import { ChangeEvent, useMemo, useRef, useState } from "react";

type Tx = { id:string; date:string; description:string; amount:number };
type Result = { vendorId:string; ledgerId:string; vendorDate:string; ledgerDate:string; vendorAmount:number; ledgerAmount:number; status:string; confidence:number; reason:string };
const vendorSample:Tx[]=[
  {id:"V001",date:"2026-08-01",description:"Packaging materials",amount:10000},{id:"V002",date:"2026-08-05",description:"Printed cartons",amount:15000},{id:"V003",date:"2026-08-10",description:"Shipping labels",amount:8000},{id:"V004",date:"2026-08-15",description:"Bubble wrap",amount:12000},{id:"V006",date:"2026-08-20",description:"Reusable crates",amount:7000},
];
const ledgerSample:Tx[]=[
  {id:"V001",date:"2026-08-01",description:"Packaging materials",amount:10000},{id:"V002",date:"2026-08-05",description:"Printed cartons",amount:14500},{id:"V003",date:"2026-08-12",description:"Shipping labels",amount:8000},{id:"L004",date:"2026-08-16",description:"Bubble wrap",amount:12000},{id:"V005",date:"2026-08-18",description:"Advance payment",amount:5000},
];
const aliases:Record<string,string[]>={id:["transaction_id","transaction id","txn_id","txn id","reference","invoice_no","invoice no"],date:["date","transaction_date","transaction date","posting_date","posting date","invoice_date"],description:["description","details","narration","memo"],amount:["amount","transaction_amount","transaction amount","value","total","invoice_amount"]};
function parseLine(line:string){const out:string[]=[];let v="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===","&&!q){out.push(v.trim());v=""}else v+=c}out.push(v.trim());return out}
function parseCsv(text:string):Tx[]{const lines=text.replace(/\r/g,"").split("\n").filter(Boolean);if(lines.length<2)throw new Error("CSV must contain a header and at least one transaction.");const heads=parseLine(lines[0]).map(x=>x.toLowerCase().trim());const idx:Record<string,number>={};Object.entries(aliases).forEach(([k,a])=>idx[k]=heads.findIndex(h=>a.includes(h)));const missing=Object.keys(idx).filter(k=>idx[k]<0);if(missing.length)throw new Error(`Missing columns: ${missing.join(", ")}`);const rows=lines.slice(1).map((line,i)=>{const c=parseLine(line),amount=Number(c[idx.amount].replace(/[₹$,]/g,"")),date=c[idx.date],id=c[idx.id].toUpperCase();if(!id||Number.isNaN(amount)||Number.isNaN(Date.parse(date)))throw new Error(`Invalid values on CSV row ${i+2}.`);return{id,date,description:c[idx.description],amount}});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error("Duplicate transaction IDs found.");return rows}
const days=(a:string,b:string)=>Math.abs((Date.parse(a)-Date.parse(b))/86400000);
const row=(v:Tx|null,l:Tx|null,status:string,confidence:number,reason:string):Result=>({vendorId:v?.id??"—",ledgerId:l?.id??"—",vendorDate:v?.date??"—",ledgerDate:l?.date??"—",vendorAmount:v?.amount??0,ledgerAmount:l?.amount??0,status,confidence,reason});
function reconcile(vendor:Tx[],ledger:Tx[],window:number){const out:Result[]=[],used=new Set<number>(),unmatched:Tx[]=[];vendor.forEach(v=>{const i=ledger.findIndex(l=>l.id===v.id);if(i<0){unmatched.push(v);return}used.add(i);const l=ledger[i],ad=v.amount-l.amount,dd=days(v.date,l.date);if(ad===0&&dd===0)out.push(row(v,l,"Exact Match",100,`ID ${v.id}, date ${v.date}, and amount ₹${v.amount.toLocaleString("en-IN")} match exactly.`));else if(ad!==0&&dd===0)out.push(row(v,l,"Amount Mismatch",90,`Same ID and date, but vendor amount ₹${v.amount.toLocaleString("en-IN")} differs from ledger amount ₹${l.amount.toLocaleString("en-IN")} by ₹${ad.toLocaleString("en-IN")}.`));else if(ad===0)out.push(row(v,l,"Date Mismatch",85,`Same ID and amount, but dates differ by ${dd} day(s): ${v.date} vs ${l.date}.`));else out.push(row(v,l,"Amount & Date Mismatch",75,`ID matches, but amount differs by ₹${ad.toLocaleString("en-IN")} and date by ${dd} day(s).`))});unmatched.forEach(v=>{const candidates=ledger.map((l,i)=>({l,i,gap:days(v.date,l.date)})).filter(x=>!used.has(x.i)&&x.l.amount===v.amount&&x.gap<=window).sort((a,b)=>a.gap-b.gap);if(candidates.length){const c=candidates[0];used.add(c.i);out.push(row(v,c.l,"Possible Match",65,`Different IDs, but ₹${v.amount.toLocaleString("en-IN")} matches and dates are ${c.gap} day(s) apart. Manual verification required.`))}else out.push(row(v,null,"Vendor Only",0,`${v.id} for ₹${v.amount.toLocaleString("en-IN")} appears in the vendor statement but not in the ledger.`))});ledger.forEach((l,i)=>{if(!used.has(i))out.push(row(null,l,"Ledger Only",0,`${l.id} for ₹${l.amount.toLocaleString("en-IN")} appears in the ledger but not in the vendor statement.`))});const p=["Vendor Only","Ledger Only","Amount & Date Mismatch","Amount Mismatch","Date Mismatch","Possible Match","Exact Match"];return out.sort((a,b)=>p.indexOf(a.status)-p.indexOf(b.status))}
const money=(n:number)=>`₹${n.toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function Home(){
  const [vendor,setVendor]=useState(vendorSample),[ledger,setLedger]=useState(ledgerSample),[vendorName,setVendorName]=useState("vendor_statement.csv"),[ledgerName,setLedgerName]=useState("internal_ledger.csv"),[window,setWindow]=useState(3),[filter,setFilter]=useState("All"),[question,setQuestion]=useState(""),[answer,setAnswer]=useState(""),[error,setError]=useState("");
  const vi=useRef<HTMLInputElement>(null),li=useRef<HTMLInputElement>(null),results=useMemo(()=>reconcile(vendor,ledger,window),[vendor,ledger,window]);const vendorTotal=results.reduce((s,r)=>s+r.vendorAmount,0),ledgerTotal=results.reduce((s,r)=>s+r.ledgerAmount,0),review=results.filter(r=>r.status!=="Exact Match").length,visible=filter==="All"?results:results.filter(r=>r.status===filter);
  async function upload(e:ChangeEvent<HTMLInputElement>,source:"vendor"|"ledger"){const file=e.target.files?.[0];if(!file)return;try{const rows=parseCsv(await file.text());if(source==="vendor"){setVendor(rows);setVendorName(file.name)}else{setLedger(rows);setLedgerName(file.name)}setError("");setAnswer("")}catch(err){setError(err instanceof Error?err.message:"Could not read the CSV.")}}
  function ask(){const q=question.toLowerCase(),id=[...new Set(results.flatMap(r=>[r.vendorId,r.ledgerId]))].filter(x=>x!=="—").sort((a,b)=>b.length-a.length).find(x=>new RegExp(`(^|\\W)${x}($|\\W)`,"i").test(question));if(id){const r=results.find(x=>x.vendorId===id||x.ledgerId===id)!;setAnswer(`${id} is classified as ${r.status} with ${r.confidence}% confidence. ${r.reason}`)}else if(/balance|difference|total/.test(q))setAnswer(`Vendor total is ${money(vendorTotal)}, ledger total is ${money(ledgerTotal)}, and the net difference is ${money(vendorTotal-ledgerTotal)}.`);else if(/priority|first|attention|review/.test(q))setAnswer("Review these first: "+results.filter(r=>r.status!=="Exact Match").slice(0,3).map(r=>`${r.vendorId==="—"?r.ledgerId:r.vendorId} (${r.status})`).join(", ")+".");else if(/unmatched|missing|only/.test(q))setAnswer("Unmatched items: "+results.filter(r=>/Only/.test(r.status)).map(r=>`${r.vendorId==="—"?r.ledgerId:r.vendorId} — ${r.status}`).join(", ")+".");else setAnswer("I answer only from verified reconciliation data. Try: “Why was V002 flagged?”, “What is the balance difference?”, or “Which items need review first?”")}
  function download(){const head=["vendor_id","ledger_id","vendor_date","ledger_date","vendor_amount","ledger_amount","difference","status","confidence","reason"],csv=[head,...results.map(r=>[r.vendorId,r.ledgerId,r.vendorDate,r.ledgerDate,r.vendorAmount,r.ledgerAmount,r.vendorAmount-r.ledgerAmount,r.status,r.confidence,r.reason])].map(a=>a.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="reconciliation_report.csv";a.click();URL.revokeObjectURL(a.href)}
  return <main><header><div><span className="eyebrow">FINANCE OPERATIONS · AI EMPLOYEE</span><h1>Vendor Reconciliation <i>Copilot</i></h1><p>Transparent matching. Grounded explanations. Human-controlled review.</p></div><div className="privacy"><b>LOCAL PROCESSING</b><span>Your CSV data stays in this browser</span></div></header>
  <section className="controls"><div className="upload" onClick={()=>vi.current?.click()}><span className="step">01</span><div><b>Vendor statement</b><small>{vendorName}</small></div><button>Choose CSV</button><input ref={vi} hidden type="file" accept=".csv" onChange={e=>upload(e,"vendor")}/></div><div className="upload" onClick={()=>li.current?.click()}><span className="step">02</span><div><b>Internal ledger</b><small>{ledgerName}</small></div><button>Choose CSV</button><input ref={li} hidden type="file" accept=".csv" onChange={e=>upload(e,"ledger")}/></div><label className="window"><span>Possible match window</span><b>{window} days</b><input type="range" min="0" max="10" value={window} onChange={e=>setWindow(+e.target.value)}/></label></section>{error&&<div className="error">{error}</div>}
  <section className="metrics"><article><span>Vendor balance</span><strong>{money(vendorTotal)}</strong><small>{vendor.length} source records</small></article><article><span>Ledger balance</span><strong>{money(ledgerTotal)}</strong><small>{ledger.length} source records</small></article><article className="accent"><span>Net difference</span><strong>{money(vendorTotal-ledgerTotal)}</strong><small>Vendor minus ledger</small></article><article><span>Requires review</span><strong>{review}</strong><small>{results.length-review} exact match</small></article></section>
  <section className="workspace"><div className="tableCard"><div className="sectionHead"><div><span className="eyebrow">RECONCILIATION OUTPUT</span><h2>Transaction review queue</h2></div><div className="actions"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{[...new Set(results.map(r=>r.status))].map(s=><option key={s}>{s}</option>)}</select><button className="download" onClick={download}>Download report ↓</button></div></div><div className="tableWrap"><table><thead><tr><th>Reference</th><th>Dates</th><th>Vendor</th><th>Ledger</th><th>Difference</th><th>Decision</th><th>Confidence</th></tr></thead><tbody>{visible.map((r,i)=><tr key={i}><td><b>{r.vendorId}</b><small>Ledger: {r.ledgerId}</small></td><td>{r.vendorDate}<small>{r.ledgerDate}</small></td><td>{money(r.vendorAmount)}</td><td>{money(r.ledgerAmount)}</td><td className={r.vendorAmount-r.ledgerAmount?"negative":""}>{money(r.vendorAmount-r.ledgerAmount)}</td><td><span className={`badge b-${r.status.toLowerCase().replaceAll(" ","-").replace("&","and")}`}>{r.status}</span><small className="reason">{r.reason}</small></td><td><div className="bar"><i style={{width:`${r.confidence}%`}}/></div><small>{r.confidence}%</small></td></tr>)}</tbody></table></div></div>
  <aside><span className="eyebrow">GROUNDED ASSISTANT</span><h2>Ask the Copilot</h2><p>Answers are generated only from the verified reconciliation table.</p><div className="suggestions"><button onClick={()=>setQuestion("Why was V002 flagged?")}>Why was V002 flagged?</button><button onClick={()=>setQuestion("Which items need review first?")}>Review priorities</button><button onClick={()=>setQuestion("What is the balance difference?")}>Balance difference</button></div><div className="chat"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about an ID, difference, or priority…"/><button onClick={ask}>Ask →</button></div>{answer&&<div className="answer"><b>COPILOT</b><p>{answer}</p></div>}<div className="assumption"><b>Scoped assumption</b><p>One currency, unique IDs, one-to-one matching. Possible matches always require human review.</p></div></aside></section><footer><b>Decision integrity:</b> Calculations use deterministic rules—not an LLM. Every flag cites its source values.</footer></main>
}
